# 生产环境配置
identifyingCode: 1
server:
  port: 80
  tomcat:
    # tomcat最大线程数，默认为200
    max-threads: 800
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 30

spring:
  redis:
    host: 127.0.0.1
    port: 6379
    password: