# 生产环境配置
identifyingCode: 1
server:
  port: 80
  tomcat:
    threads:
      # tomcat最大线程数，默认为200
      max: 800
      # Tomcat启动初始化的线程数，默认值10
      min-spare: 30

spring:
  redis:
    host: 127.0.0.1
    port: 6379
    password: